server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intraday
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# Custom User Password for Spring security
#  security:
#    user:
#      name: UserAdmin
#      password: UserAdmin

security:
  user:
    name: UserAdmin
    password: UserAdmin


